### ISSUE TITLE
新建工单-没有设置工作流字段

### ISSUE THREAD

**Issue by xiahuhu1** [itimor/one-workflow#14]
我这边在系统里面新建了一个开发角色的账号，也添加了对应的权限，但是是在新建工单的时候提示”没有设置工作流字段“，请问还需要在哪里进行授权操作码？

![5EFA8BBE-7B72-41A8-BFAB-F87353A7D7FD](https://user-images.githubusercontent.com/38675377/121990058-bc89bd80-cdcf-11eb-8ece-16444da22d69.png)
![74A04366-ADB5-4EF8-9789-26584427203F](https://user-images.githubusercontent.com/38675377/121990078-c6132580-cdcf-11eb-9208-8f6a9ad6dc91.png)
![68D34A0D-67BD-4659-A6FD-A7FEC5E0966F](https://user-images.githubusercontent.com/38675377/121990095-cc090680-cdcf-11eb-93a8-addff9a31363.png)

**Comment by itimor** [comment]
再试下

**Comment by itimor** [comment]
![image](https://user-images.githubusercontent.com/24787591/122178568-4497c200-ceb9-11eb-8d8e-06b38e03700e.png)
view工作流字段和状态的权限没加

**Comment by itimor** [comment]
重新拉下，初始化脚本加了
